#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:
# to copy a file to remote server:
# scp myfile.txt user@remote:/path/to/destination
# scp -i /path/to/private/key myfile.txt user@remote:/path/to/destination

# -n checks if the third argument ($3) is not empty.

if [ "$#" -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
current_file="$1"
user="$3"
ip="$2"
private_key_path="$4"

    scp  -i $private_key_path -o StrictHostKeyChecking=no $current_file "$user@$ip:~/"
fi
