#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:
# to copy a file to remote server:
# scp myfile.txt user@remote:/path/to/destination
# scp -i /path/to/private/key myfile.txt user@remote:/path/to/destination

# -n checks if the third argument ($3) is not empty.
i=0

for i in $@
do 
((i++))
done 
if [ "$i" -lt 5 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp  -i "$4" "$1" "$3@$2:~/"  -o StrictHostKeyChecking=no
fi
