#!/usr/bin/env bash
# install nginx and update its welcome file

sudo apt-get update
sudo apt-get install nginx -y
sudo echo "<h1>Hello World!</h1>" >> /var/www/html/index.html

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
