#!/usr/bin/env bash
# redirect user to anther website

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

old_line="server_name _;"
new_line="server_name foash.tech;\n        location /redirect_me { \n       return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }"

sudo sed -i "s|${old_line}|${new_line}|g" /etc/nginx/sites-enabled/default 

sudo service nginx restart
service nginx reload
