#!/usr/bin/env bash
# add_header directive to the server when http header requested

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

sed -i "30i\ \n        add_header X-Served-By $HOSTNAME;\n" /etc/nginx/nginx.conf

sudo service nginx reload
