#!/usr/bin/env bash
# installl load balancer and configure it

sudo apt-get update
sudo apt-get install haproxy -y

frontend="frontend http-in\n        bind *:80\n        default_backend servers\n"
backend="backend servers\n        balance roundrobin\n        server 381421-web-01 52.91.182.174:80 check\n        server 381421-web-02 52.91.151.229:80 check\n"

sudo tee -a /etc/haproxy/haproxy.cfg << EOF
$frontend
$backend
EOF
# -a: An option for tee that appends the input to the end of the file
# you can use any unique string instead of EOF as a delimiter
# For example, you could use END_OF_TEXT as your delimiter:
# cat <<END_OF_TEXT
# This is a multi-line
# text block.
# END_OF_TEXT
sudo service haproxy start
