#!/usr/bin/env bash
# installl load balancer and configure it

sudo apt-get update
sudo apt-get install haproxy -y

echo -e "
frontend http-in
        bind *:80
        default_backend servers

backend servers
        balance roundrobin
        server 381421-web-01 52.91.182.174:80 check
        server 381421-web-02 52.91.151.229:80 check
" >> /etc/haproxy/haproxy.cfg

#  -e     enable interpretation of backslash escapes

# sudo tee -a /etc/haproxy/haproxy.cfg << EOF
# $frontend
# EOF

# -a: An option for tee that appends the input to the end of the file
# you can use any unique string instead of EOF as a delimiter
# For example, you could use END_OF_TEXT as your delimiter:
# cat <<END_OF_TEXT
# This is a multi-line
# text block.
# END_OF_TEXT

echo "ENABLED=1" >> /etc/default/haproxy

#sudo haproxy -c -f /etc/haproxy/haproxy.cfg
# -c to check for syntax error
# -f /path/to/file
sudo service haproxy restart
