#!/usr/bin/env bash
# install and configure ufw (uncomplicated fire wall) and forward incoming traffic on port 8080 to port 80
# step 1 uncomment this line: #net/ipv4/ip_forward=1 in /etc/ufw/sysctl.conf file
# use | as a separator cause / is used in the command internally as a path

sudo apt update
sudo apt install ufw -y
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 8080/tcp
sudo sed -i 's|#net/ipv4/ip_forward=1|net/ipv4/ip_forward=1|g' /etc/ufw/sysctl.conf
sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
sudo iptables-save > /etc/iptables/rules.v4
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw status
