#!/usr/bin/env bash
# install and configure ufw (uncomplicated fire wall) and forward incoming traffic on port 8080 to port 80
# step 1 uncomment this line: #net/ipv4/ip_forward=1 in /etc/ufw/sysctl.conf file
# use | as a separator cause / is used in the command internally as a path

sudo apt update

# Install ufw
sudo apt install ufw -y

# Enable ufw
sudo ufw enable

# Allow SSH, HTTP, HTTPS
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Allow port 8080
sudo ufw allow from 8080/tcp to 80/tcp

# Check ufw status
sudo ufw status
