#!/usr/bin/env bash
#chang ip address for my local machine and facebook.com

sed -i "s/127.0.0.1/127.0.0.2/g" /etc/hosts
sed -i "s/157.240.11.35/8.8.8.8/g" /etc/hosts

#192.168.1.2	localhost
#8.8.8.8		facebook.com
