#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.

# Example:

# sylvain@ubuntu$ ./1-show_attached_IPs | cat -e
# 10.0.2.15$
# 127.0.0.1$

ifconfig | grep -w 'inet' | awk '{print $2}'
