#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key ~/.ssh/school
#  -i used for specify the identity file (private key)
ssh -i ~/.ssh/school ubuntu@52.91.182.174
